version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/flask/Dockerfile
    image: pashakhomchenko/scribe-flask
    command: flask --app scribe --debug run --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
    ports:
      - 5000:5000

  transcribe:
    build:
      context: .
      dockerfile: dockerfiles/transcribe/Dockerfile
    image: pashakhomchenko/scribe-transcribe
    volumes:
      - .:/app
