version: '3.8'

services:
  celery-worker:
    image: pashakhomchenko/scribe-celery
    command: celery -A scribe.tasks.app worker -l info
    volumes:
      - mydata:/app/files
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 8G
          devices:
            - capabilities: [ "gpu" ]
              count: 1

volumes:
  mydata:
    driver_opts:
      # Access point configuration
      uid: 0
      gid: 0
