version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/flask/Dockerfile
    command: flask --app scribe --debug run --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  celery-worker:
    build:
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    command: celery -A scribe.tasks.app worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  flower:
    build:
      context: .
      dockerfile: dockerfiles/flower/Dockerfile
    command: celery -A app.celery flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: redis:alpine
    env_file:
      - .env
    volumes:
      - .:/app
